// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU7p-bFdpRbMtWK6i9xWk4PNEItZ7zodk',
    appId: '1:607615760022:web:23c2c9186f8c9af9a274b7',
    messagingSenderId: '607615760022',
    databaseURL:
        'https://hexagonal-sliding-puzzle-default-rtdb.europe-west1.firebasedatabase.app/',
    projectId: 'hexagonal-sliding-puzzle',
    authDomain: 'hexagonal-sliding-puzzle.firebaseapp.com',
    storageBucket: 'hexagonal-sliding-puzzle.appspot.com',
    measurementId: 'G-XXV8ZBW9WM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtqEUg2bA9QQ4jTrRhR_ED28I2fthg5I0',
    appId: '1:607615760022:android:a6f095de6514b842a274b7',
    messagingSenderId: '607615760022',
    projectId: 'hexagonal-sliding-puzzle',
    storageBucket: 'hexagonal-sliding-puzzle.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoMHBwFXvzAXFg8lZT120nTKBbqcaMjOk',
    appId: '1:607615760022:ios:0ad8732ae7458ee8a274b7',
    messagingSenderId: '607615760022',
    projectId: 'hexagonal-sliding-puzzle',
    storageBucket: 'hexagonal-sliding-puzzle.appspot.com',
    iosClientId:
        '607615760022-pboebos21nquf58g8q8e7k18njouh33v.apps.googleusercontent.com',
    iosBundleId: 'com.policy.hexagonalslidingpuzzle',
  );
}
